services:
  - type: web
    name: nextra-pro-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nextra-pro-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USER
        value: vvfd
      - key: ADMIN_PASSWORD
        value: "12321"
      - key: CORS_ORIGIN
        value: "*"

databases:
  - name: nextra-pro-db
    plan: free
